### ISSUE TITLE
Explore differences between dry spells from CHIRPS and ARC2

### ISSUE THREAD

**Issue by hannahker** [OCHA-DAP/pa-anticipatory-action#171]
If using ARC2 over CHIRPS for the Malawi observational trigger, we need to make an effort to explain discrepancies between the historical dry spells that are identified by these two data sources. The most obvious difference is that these datasets have differing resolutions (0.05 and 0.1 degrees, respectively), but it's not clear what kind of impact this has. 

In addition to a basic literature review, we should explore and compare the daily precipitation values for both datasets during cases where a dry spell is identified by one source but not the other. So for example, if CHIRPS identifies a dry spell between Dec 1-Dec 20 but ARC2 doesn't, what is going on with the precipitation values from ARC2 during this time? This could probably be accomplished by basic visualisation of the daily precipitation time series from both sources during a time period of interest (akin to what we've already done when comparing GloFAS discharge between stations - [here](https://github.com/OCHA-DAP/pa-anticipatory-action/blob/develop/analyses/malawi/flooding_trigger/05_mwi_station_correlation.md)).

Any systematic differences revealed as result of this analysis may have to be accounted for in our use of ARC2 for the trigger.

**Comment by hannahker** [comment]
Need to validate that these are the most appropriate and up-to-date versions of the CHIRPS and ARC2 dry spells events: 

- ARC2: `public/exploration/mwi/arc2/mwi_arc2_dry_spells.csv`
- CHIRPS: `dry_spells_during_rainy_season_list_2000_2021_mean_back.csv`

Both datasets should be: 
- Aggregated to ADM2
- Calculated using the daily mean of all cells within an admin region
- Filtered to only include dry spells during the rainy season

@Tinkaa could you confirm that I've found the right files?

**Comment by Tinkaa** [comment]
Yes great job idenitying those in the mess! Trying to open `mwi_arc2_dry_spells.csv` gave me a corrupted file error, so I just recomputed it using the notebook and hope it is correct now. You might want to recompute with 2021 data though. also this arc2 file now contains dry spells outside the rainy season as well. 

Few thoughts:
- For the comparison of arc2 and chirps a density/bias plot could maybe be helpful? to see if one is consistently giving higher values than the other
- the aggreagtion to adm2 for arc2 and chirps with the current code is now done by taking all cells with their **center** within the adm2 boundary (see [rasterstats documentation](https://pythonhosted.org/rasterstats/manual.html#rasterization-strategy)). Maybe a quick check if this is valid with the lower resolution would be valuable.

**Comment by hannahker** [comment]
And precipitation: 

ARC2: `public/exploration/mwi/arc2/mwi_arc2_precip_long.csv`
