### ISSUE TITLE
HDX broken links

### ISSUE THREAD

**Issue by caldwellst** [OCHA-DAP/pa-anticipatory-action#199]
While reviewing the HDX files for [CHIRPS uploaded in August](https://data.humdata.org/dataset/historical-dry-spells-in-malawi), I noticed that the metadata page links to now broken URLs. This has occurred because of the switch from country names to ISO3 codes in the file pathing.

In this example, these are:

- https://ocha-dap.github.io/pa-anticipatory-action/analyses/malawi/docs/mwi_historical_dry_spells_description.html which is actually broken
- https://github.com/OCHA-DAP/pa-anticipatory-action/blob/a9472e6ea765b47d7017d78c0ae56f51c0dacd0a/analyses/malawi/dryspells_trigger/01_chirps_dry_spell_detection.R which works but should likely be re-routed in a similar manner in case that files is updated or changed.

Tagging everyone in the issue as would be good to review everyone's HDX uploads to ensure that links are still actively working. (I know necessarily isn't repo related but figured would be a good way to flag to everyone, let me know if y'all got other processes!)

**Comment by Tinkaa** [comment]
Oops, good catch, thanks. Thought I updated everything but apparently forgot this one. Not sure if we can come up with a better system for this? (we will have to change all the links again once we create separate repos..) 

Regarding the link to the code, I updated it now to the newest version. Though, I do think it is good to work with these permalinks, such that they always remain working.

**Comment by joseepoirier** [comment]
I don't think there were other HDX uploads. 

Unfortunately, the price for improving our repos through refactoring is broken links elsewhere. Maybe we should have a list of all files uploaded to HDX that we can use as a checklist in the future to make sure their links are still active after changes?

**Comment by caldwellst** [comment]
That's a good idea Josée. I have just added a very simple Google Sheet to the Drive which others can edit, move, and view if you want.

https://docs.google.com/spreadsheets/d/1suNP25d3SEwdqrDDb9PAvyCkVDthNCh1g0dbTxV2-1M/edit?usp=sharing

It's currently in the PA folder, but could be moved, just not sure where the best location might be.

If no other HDX uploads, will close this issue now as Tinka has edited hers!
