### ISSUE TITLE
Malawi map output for predictive trigger

### ISSUE THREAD

**Issue by Tinkaa** [OCHA-DAP/pa-anticipatory-action#234]
Hi @joseepoirier @caldwellst ,
Related to #232 , we also got the request to create a map for the predictive trigger. I have been playing a bit with it and came up with the idea shown below. This map shows the forecasted monthly precipitation with a diverging scheme where the color changes at the threshold (=210 mm). 

I chose to display an area around Malawi as well, as it gives a bit more context. However, we could also choose to only show a smaller area or even only show the cells that are included in the computation of the trigger (which is the second image). 

However, I am struggling a little bit with what the map conveys and what it will be used for. 
In this case it might seem from the map that the trigger should be met. However, the trigger wasn't met in this case (ofc I chose the trickiest example). The reason for that is that only 2 cells are included in the computation, the ones shown in the second image, and in this case the mean of those two cells is larger than 210 mm. 

@joseepoirier @caldwellst what are your opinions? Should we produce a map and if so, is this a good format or do you have other ideas? 

To build upon the voting, I would currently vote for 
- Map with whole area
- No map (if this is an option)
- Map with only selected cells

![afbeelding](https://user-images.githubusercontent.com/12556634/140479303-5286f844-90ce-4e86-b118-deb7db4e238d.png)
![afbeelding](https://user-images.githubusercontent.com/12556634/140481372-31eb9905-e2e4-4f24-ad21-5a8f88183fe9.png)

**Comment by joseepoirier** [comment]
Thanks Tinka. I believe @caldwellst has been working on this as well, so let's make sure to coordinate the efforts. This map must be ready by next week (ie code PR-ed and merged by Friday 12 Nov) as we may need to produce it as early as Monday 15 Nov. Please do loop in @milanoleonardo if needed during my absence.

The predictive trigger is based on the 50%+ likelihood of <210mm of rain in the Southern region (adm1). The email announcing it was met is to include the forecast for reference and transparency. The top map will convey the main message and provide some context around it too, without raising too many questions about the methodology (which are welcome, but not in response to an activation announcing email.)

**Comment by caldwellst** [comment]
Thanks @Tinkaa, agree here with your voting and the suggestion by @joseepoirier. Since my assumption is that we are only producing this map and sending the e-mail if we reach the trigger, then I don't think we need to worry about confusing visualisations you raise.

**Comment by joseepoirier** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Prepare map for predictive trigger activation email - MWI](https://trello.com/c/m6jfJm8H/4-prepare-map-for-predictive-trigger-activation-email-mwi)

**Comment by Tinkaa** [comment]
In the end we settled on a map showing the cells within the Southern region and using a diverging colorscheme. This can be improved for v2
