### ISSUE TITLE
[floodscan] add flexibility for area statistics

### ISSUE THREAD

**Issue by Tinkaa** [OCHA-DAP/pa-anticipatory-action#71]
- Would be nice to get summary stats by a subset of admin regions to speed things up (eg. if you only care about the results for one area in a country)
- Could also be nice to get the results from a buffer around a point (eg. a GloFAS station), so that we're avoiding using artificial boundaries as much as possible.

**Comment by Tinkaa** [comment]
@hannahker is this being implemented by #70 ?

**Comment by hannahker** [comment]
No, but #79 is a more generalized version of this!

**Comment by Tinkaa** [comment]
@hannahker Meaning we can do these two things with the additions of that code?

**Comment by Tinkaa** [comment]
@hannahker this is ages ago, but I think this has been implemented, therefore closing this issue. Let me know if you think differently.
