### ISSUE TITLE
Utils function for computing stats within polygon

### ISSUE THREAD

**Issue by Tinkaa** [OCHA-DAP/pa-anticipatory-action#94]
For many datasets we are computing statistics of raster files within a region. 
We have an outdated function for this in `general_utils` named `compute_raster_statistics`. But in practice we (or I) have been defining a new function for each use case. 

So goal would be to see if we can capture all use cases in one general function. 

Also links to #85 to try to make computing these stats faster.

**Comment by turnerm** [comment]
@Tinkaa can this be closed now?

**Comment by Tinkaa** [comment]
Yes addressed in #146
